name: manual upload

on:
  workflow_dispatch:
    paths:
      - 'GaluhadPlugins/Pets.plugin'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install xmlstarlet
        run: sudo apt update && sudo apt install -y xmlstarlet

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Extract current version from Pets.plugin
        id: current_version
        run: |
          version=$(xmlstarlet sel -T -t -v "//Plugin/Information/Version" "GaluhadPlugins/Pets.plugin")
          echo "current_version=U$version" >> $GITHUB_OUTPUT
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          MD5PASSWORD: ${{ secrets.MD5PASSWORD }}
        run: UPDATE=${{ steps.current_version.outputs.current_version }} python update_lotro_interface.py
